# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_id', models.IntegerField(default=0)),
                ('product_price', models.IntegerField(default=0)),
                ('price_url', models.URLField()),
            ],
        ),
    ]
