# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Varients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Xtra-Small', 'Xtra-Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Xtra-Large', 'Xtra-Large')], default='Small', max_length=20)),
                ('SKU_Code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shirt.Sno'),
        ),
        migrations.AddField(
            model_name='product_varients',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shirt.Sno'),
        ),
    ]
